class CurrencyCode {
    static get codes() {
        return {
            1: 'CNY',
            2: 'USD',
            3: 'KRW',
            4: 'MYR',
            5: 'SGD',
            6: 'JPY',
            7: 'THB',
            8: 'IDR',
            9: 'VND',
            10: 'AUD',
            11: 'GBP',
            12: 'CHF',
            13: 'MXN',
            14: 'CAD',
            15: 'RUB',
            16: 'INR',
            17: 'RON',
            18: 'DKK',
            19: 'NOK',
            20: 'NTD',
            21: 'COP',
            22: 'MMK',
            23: 'PLN',
            24: 'HRK',
            25: 'CZK',
            26: 'HUF',
            27: 'ZAR',
            28: 'SEK',
            29: 'NZD',
            30: 'TRY',
            31: 'BND',
            32: 'KHR',
            33: 'USDT',
            34: 'BDT',
            35: 'EUR',
            36: 'BRL',
            37: 'PHP',
            38: 'TND',
            39: 'TWD',
            40: 'UAH',
            41: 'PKR',
            42: 'HKD',
            43: 'MAD',
            44: 'EGP',
            45: 'ZMW',
            46: 'NPR',
            47: 'KSH',
            48: 'AED',
            49: 'LAK',
            50: 'NGN',
            51: 'KES',
            52: 'UGX',
            53: 'SAR',
            54: 'AZN',
            55: 'BGN',
            56: 'ARS',
            57: 'AMD',
        };
    }

    static getDescription(code) {
        return this.codes[code] || 'Unknown currency code';
    }
}

module.exports = CurrencyCode;
